### ISSUE TITLE
Deliver part I

### ISSUE THREAD

**Issue by maria** [maria/github-training#2]
### Need

``` gherkin
As a GitHub user 
I want to deliver the training
In order for the entire team to know how to use it
```
### Deliverables
- All of my colleagues will know how to open Issues
### Solution

Create an interactive video.
### TODOs
-  [ ] Make training video
-  [ ] Share the video with everyone
-  [ ] Check if everyone understood the material
